version: "3.8"

# remove this line if you don't need a volume to map your dependencies
# Check how to cache the build
volumes:
  cargo:

services:
  package:
    image: rust:1
    tty: true
    stdin_open: true
    working_dir: /home/package
    environment:
      - MEILISEARCH_URL=http://meilisearch:7700
      - MEILISEARCH_EXPORT_URL=http://meilisearch_export:7700
      - CARGO_HOME=/vendor/cargo
    depends_on:
      - meilisearch
      - meilisearch_export
    links:
      - meilisearch
      - meilisearch_export
    volumes:
      - ./:/home/package
      - cargo:/vendor/cargo

  meilisearch:
    image: getmeili/meilisearch-enterprise:latest
    command: meilisearch --experimental-allowed-ip-networks "172.16.0.0/12" #docker internal IPs
    ports:
      - "7700"
    environment:
      - MEILI_MASTER_KEY=masterKey
      - MEILI_NO_ANALYTICS=true

  meilisearch_export:
    image: getmeili/meilisearch-enterprise:latest
    ports:
      - "7700"
    environment:
      - MEILI_MASTER_KEY=masterKey
      - MEILI_NO_ANALYTICS=true
