name: Publish to crates.io
on:
  push:
    tags:
      - v*

jobs:
  publish:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hecrj/setup-rust-action@master
        with:
          rust-version: stable
      - name: Check release validity
        run: sh .github/scripts/check-release.sh
      - name: Build meilisearch crate
        run: cargo build --release
      - name: Build meilisearch crate
        run: |-
          cd meilisearch-index-setting-macro
          cargo build --release
      - name: Login
        run: cargo login ${{ secrets.CRATES_TOKEN }}
      - name: Publish meilisearch-index-setting-macro crate to crates.io
        run: |-
          cd meilisearch-index-setting-macro
          cargo publish
      - name: Publish meilisearch crate to crates.io
        run: cargo publish
